version: "3.5"
name: raopics
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    command: [nginx, "-g", "daemon off;"]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    tty: true
    build: ./
    environment:
      LIBRARY: /library # volumes中的地址
      PORT: 9600
    volumes:
      # 本地挂载library地址
      - /Users/qymeet/Pictures/rao.library/images:/library/images:ro
      - /Users/qymeet/Pictures/rao.library/metadata.json:/library/metadata.json:ro
      - /Users/qymeet/Pictures/rao.library/tags.json:/library/tags.json:ro
      # - /Users/qymeet/Pictures/rao.library/raopics.db:/library/raopics.db # 首次运行需要注释这行，
      # 因为本地不存在该文件，docker会以文件夹的形式创建，导致后续步骤报错
      # 首次执行完成后，在docker的files中会新增这个文件 `library/raopics.db`，
      # 你可以把它导出到本地，放在`/Users/qymeet/Pictures/rao.library`文件夹下。
      # 下次启动时就会节省很多时间。

  rua:
    image: meetqy/raopics-rua
    environment:
      PORT: 9601
